import type {
  OpenSourceCapability,
  OpenSourceToolCategory,
  OpenSourceToolDefinition,
  OpenSourceToolId,
  OpenSourceToolPolicyStatus,
  OpenSourceToolRuntime
} from "@periscan/shared";

type ExpansionTool = {
  binaryName: string | null;
  category: OpenSourceToolCategory;
  defaultVersion: string;
  displayName: string;
  dockerImage: string | null;
  docsUrl: string;
  gitRepo: string | null;
  license: string;
  licenseUrl?: string;
  moduleIds: string[];
  notes: string;
  npmPackage?: string | null;
  pipPackage?: string | null;
  policyStatus: OpenSourceToolPolicyStatus;
  runtimePreference: OpenSourceToolRuntime[];
  toolId: OpenSourceToolId;
};

const EXPANSION_TOOLS: ExpansionTool[] = [
  {
    binaryName: "brakeman",
    category: "ExposureValidation",
    defaultVersion: "7.0.2",
    displayName: "Brakeman",
    dockerImage: "presidentbeef/brakeman",
    docsUrl: "https://brakemanscanner.org/",
    gitRepo: "https://github.com/presidentbeef/brakeman.git",
    license: "MIT",
    moduleIds: ["brakeman.ruby_sast"],
    notes: "Ruby on Rails SAST. Live Community engine; MIT.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "brakeman"
  },
  {
    binaryName: "horusec",
    category: "ExposureValidation",
    defaultVersion: "2.9.0",
    displayName: "Horusec",
    dockerImage: "horuszub/horusec-cli",
    docsUrl: "https://horusec.io/",
    gitRepo: "https://github.com/ZupIT/horusec.git",
    license: "Apache-2.0",
    moduleIds: ["horusec.multi_sast"],
    notes: "Multi-language SAST orchestrator. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "horusec"
  },
  {
    binaryName: "dependency-check",
    category: "Dependency",
    defaultVersion: "12.1.0",
    displayName: "OWASP Dependency-Check",
    dockerImage: "owasp/dependency-check",
    docsUrl: "https://owasp.org/www-project-dependency-check/",
    gitRepo: "https://github.com/dependency-check/DependencyCheck.git",
    license: "Apache-2.0",
    moduleIds: ["dependency_check.sca"],
    notes: "OWASP SCA. Live Community engine; Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "dependency-check"
  },
  {
    binaryName: "talisman",
    category: "Secrets",
    defaultVersion: "1.32.0",
    displayName: "Talisman",
    dockerImage: "thoughtworks/talisman",
    docsUrl: "https://thoughtworks.github.io/talisman/",
    gitRepo: "https://github.com/thoughtworks/talisman.git",
    license: "Apache-2.0",
    moduleIds: ["talisman.repo_secrets"],
    notes: "Thoughtworks pre-commit secrets. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "talisman"
  },
  {
    binaryName: "kingfisher",
    category: "Secrets",
    defaultVersion: "1.0.0",
    displayName: "Kingfisher",
    dockerImage: null,
    docsUrl: "https://github.com/mongodb/kingfisher",
    gitRepo: "https://github.com/mongodb/kingfisher.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "MongoDB Kingfisher secrets scanner. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "kingfisher"
  },
  {
    binaryName: "polaris",
    category: "IaC",
    defaultVersion: "9.6.0",
    displayName: "Polaris",
    dockerImage: "quay.io/fairwinds/polaris",
    docsUrl: "https://www.fairwinds.com/polaris",
    gitRepo: "https://github.com/FairwindsOps/polaris.git",
    license: "Apache-2.0",
    moduleIds: ["polaris.k8s_posture"],
    notes: "Kubernetes workload posture. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "polaris"
  },
  {
    binaryName: "kubeaudit",
    category: "IaC",
    defaultVersion: "0.22.2",
    displayName: "kubeaudit",
    dockerImage: "shopify/kubeaudit",
    docsUrl: "https://github.com/Shopify/kubeaudit",
    gitRepo: "https://github.com/Shopify/kubeaudit.git",
    license: "MIT",
    moduleIds: ["kubeaudit.k8s_posture"],
    notes: "Shopify Kubernetes audit. MIT.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "kubeaudit"
  },
  {
    binaryName: "dive",
    category: "SupplyChain",
    defaultVersion: "0.12.0",
    displayName: "dive",
    dockerImage: "wagoodman/dive",
    docsUrl: "https://github.com/wagoodman/dive",
    gitRepo: "https://github.com/wagoodman/dive.git",
    license: "MIT",
    moduleIds: [],
    notes: "Image layer explorer. Installable; MIT. Needs an image ref to scan.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "dive"
  },
  {
    binaryName: "clair",
    category: "SupplyChain",
    defaultVersion: "4.7.4",
    displayName: "Clair",
    dockerImage: "quay.io/projectquay/clair",
    docsUrl: "https://github.com/quay/clair",
    gitRepo: "https://github.com/quay/clair.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Quay image CVE index. Apache-2.0. Service-style; install the CLI/image.",
    policyStatus: "Enabled",
    runtimePreference: ["docker"],
    toolId: "clair"
  },
  {
    binaryName: "cloudlist",
    category: "ASV_EASM",
    defaultVersion: "1.2.0",
    displayName: "cloudlist",
    dockerImage: "projectdiscovery/cloudlist",
    docsUrl: "https://github.com/projectdiscovery/cloudlist",
    gitRepo: "https://github.com/projectdiscovery/cloudlist.git",
    license: "MIT",
    moduleIds: ["cloudlist.cloud_assets"],
    notes: "ProjectDiscovery cloud asset enum. MIT. Runner when credentials exist.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "cloudlist"
  },
  {
    binaryName: "parliament",
    category: "CloudSecurity",
    defaultVersion: "1.6.2",
    displayName: "Parliament",
    dockerImage: null,
    docsUrl: "https://github.com/duo-labs/parliament",
    gitRepo: "https://github.com/duo-labs/parliament.git",
    license: "BSD-3-Clause",
    moduleIds: ["parliament.iam_policy"],
    notes:
      "AWS IAM policy linter. Live Community engine; BSD-3-Clause. Lints authorized policy documents, not live AWS accounts.",
    pipPackage: "parliament",
    policyStatus: "Enabled",
    runtimePreference: ["pip", "binary"],
    toolId: "parliament"
  },
  {
    binaryName: "katana",
    category: "NetworkRecon",
    defaultVersion: "1.1.0",
    displayName: "katana",
    dockerImage: "projectdiscovery/katana",
    docsUrl: "https://github.com/projectdiscovery/katana",
    gitRepo: "https://github.com/projectdiscovery/katana.git",
    license: "MIT",
    moduleIds: ["katana.web_crawl"],
    notes: "Authorized-scope crawler. MIT. InternalRunner. Not an exploit kit.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "katana"
  },
  {
    binaryName: "assetfinder",
    category: "ASV_EASM",
    defaultVersion: "0.1.1",
    displayName: "assetfinder",
    dockerImage: null,
    docsUrl: "https://github.com/tomnomnom/assetfinder",
    gitRepo: "https://github.com/tomnomnom/assetfinder.git",
    license: "MIT",
    moduleIds: [],
    notes: "Passive related-domain finder. MIT.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "assetfinder"
  },
  {
    binaryName: "gau",
    category: "ASV_EASM",
    defaultVersion: "2.2.3",
    displayName: "gau",
    dockerImage: "sxcurity/gau",
    docsUrl: "https://github.com/lc/gau",
    gitRepo: "https://github.com/lc/gau.git",
    license: "MIT",
    moduleIds: [],
    notes: "Known-URL harvest from public sources. MIT. Authorized domains only.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "gau"
  },
  {
    binaryName: "crowdsec",
    category: "DetectionRule",
    defaultVersion: "1.6.4",
    displayName: "CrowdSec",
    dockerImage: "crowdsecurity/crowdsec",
    docsUrl: "https://www.crowdsec.net/",
    gitRepo: "https://github.com/crowdsecurity/crowdsec.git",
    license: "MIT",
    moduleIds: [],
    notes: "Collaborative IDS. MIT. Agent install; not a live attack pack.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "crowdsec"
  },
  {
    binaryName: "zeek",
    category: "DetectionRule",
    defaultVersion: "7.0.0",
    displayName: "Zeek",
    dockerImage: "zeek/zeek",
    docsUrl: "https://zeek.org/",
    gitRepo: "https://github.com/zeek/zeek.git",
    license: "BSD-3-Clause",
    moduleIds: [],
    notes: "Network telemetry. BSD-3-Clause. Install the sensor; not live exploit.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "zeek"
  },
  {
    binaryName: "tfsec",
    category: "IaC",
    defaultVersion: "1.28.10",
    displayName: "tfsec",
    dockerImage: "aquasec/tfsec",
    docsUrl: "https://aquasecurity.github.io/tfsec/",
    gitRepo: "https://github.com/aquasecurity/tfsec.git",
    license: "MIT",
    moduleIds: ["tfsec.iac_posture"],
    notes: "Terraform SAST (now Trivy-aligned). MIT.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "tfsec"
  },
  {
    binaryName: "cfn_nag",
    category: "IaC",
    defaultVersion: "0.8.10",
    displayName: "cfn-nag",
    dockerImage: "stelligent/cfn_nag",
    docsUrl: "https://github.com/stelligent/cfn_nag",
    gitRepo: "https://github.com/stelligent/cfn_nag.git",
    license: "MIT",
    moduleIds: ["cfn_nag.cloudformation"],
    notes: "CloudFormation lint. MIT.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "cfn-nag"
  },
  {
    binaryName: "cfn-lint",
    category: "IaC",
    defaultVersion: "1.22.0",
    displayName: "cfn-lint",
    dockerImage: null,
    docsUrl: "https://github.com/aws-cloudformation/cfn-lint",
    gitRepo: "https://github.com/aws-cloudformation/cfn-lint.git",
    license: "MIT",
    moduleIds: ["cfn_lint.cloudformation"],
    notes: "AWS CloudFormation linter. Live Community engine; MIT.",
    pipPackage: "cfn-lint",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "pip"],
    toolId: "cfn-lint"
  },
  {
    binaryName: "tflint",
    category: "IaC",
    defaultVersion: "0.54.0",
    displayName: "TFLint",
    dockerImage: "ghcr.io/terraform-linters/tflint",
    docsUrl: "https://github.com/terraform-linters/tflint",
    gitRepo: "https://github.com/terraform-linters/tflint.git",
    license: "MPL-2.0",
    moduleIds: [],
    notes: "Terraform linter. MPL-2.0. Installable.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "tflint"
  },
  {
    binaryName: "kyverno",
    category: "IaC",
    defaultVersion: "1.13.0",
    displayName: "Kyverno CLI",
    dockerImage: "ghcr.io/kyverno/kyverno-cli",
    docsUrl: "https://kyverno.io/",
    gitRepo: "https://github.com/kyverno/kyverno.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Kubernetes policy CLI. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "kyverno"
  },
  {
    binaryName: "notation",
    category: "SupplyChain",
    defaultVersion: "1.2.0",
    displayName: "Notation",
    dockerImage: "ghcr.io/notaryproject/notation",
    docsUrl: "https://notaryproject.dev/",
    gitRepo: "https://github.com/notaryproject/notation.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Notary/notation image signing. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "notation"
  },
  {
    binaryName: "in-toto",
    category: "SupplyChain",
    defaultVersion: "2.2.0",
    displayName: "in-toto",
    dockerImage: null,
    docsUrl: "https://in-toto.io/",
    gitRepo: "https://github.com/in-toto/in-toto.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Supply-chain layout verification. Apache-2.0.",
    pipPackage: "in-toto",
    policyStatus: "Enabled",
    runtimePreference: ["pip", "binary"],
    toolId: "in-toto"
  },
  {
    binaryName: "bundler-audit",
    category: "Dependency",
    defaultVersion: "0.9.2",
    displayName: "bundler-audit",
    dockerImage: null,
    docsUrl: "https://github.com/rubysec/bundler-audit",
    gitRepo: "https://github.com/rubysec/bundler-audit.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/rubysec/bundler-audit/blob/master/LICENSE.txt",
    moduleIds: [],
    notes: "RubySec lockfile audit. GPL-3.0 — Engine Lab license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["binary", "git"],
    toolId: "bundler-audit"
  },
  {
    binaryName: "mix",
    category: "ExposureValidation",
    defaultVersion: "0.13.0",
    displayName: "Sobelow",
    dockerImage: null,
    docsUrl: "https://github.com/nccgroup/sobelow",
    gitRepo: "https://github.com/nccgroup/sobelow.git",
    license: "Apache-2.0",
    moduleIds: ["sobelow.elixir_sast"],
    notes: "Elixir/Phoenix SAST. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "sobelow"
  },
  {
    binaryName: "nancy",
    category: "Dependency",
    defaultVersion: "1.0.46",
    displayName: "Nancy",
    dockerImage: "sonatypecommunity/nancy",
    docsUrl: "https://github.com/sonatype-nexus-community/nancy",
    gitRepo: "https://github.com/sonatype-nexus-community/nancy.git",
    license: "Apache-2.0",
    moduleIds: ["nancy.go_advisories"],
    notes: "Go.sum OSS Index audit. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "nancy"
  },
  {
    binaryName: "popeye",
    category: "CloudSecurity",
    defaultVersion: "0.21.3",
    displayName: "Popeye",
    dockerImage: "derailed/popeye",
    docsUrl: "https://popeyecli.io/",
    gitRepo: "https://github.com/derailed/popeye.git",
    license: "Apache-2.0",
    moduleIds: ["popeye.cluster_sanitizer"],
    notes: "Live cluster sanitizer. Apache-2.0. Needs kubeconfig.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "popeye"
  },
  {
    binaryName: "tracee",
    category: "DetectionRule",
    defaultVersion: "0.22.0",
    displayName: "Tracee",
    dockerImage: "aquasec/tracee",
    docsUrl: "https://aquasecurity.github.io/tracee/",
    gitRepo: "https://github.com/aquasecurity/tracee.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "eBPF runtime detection. Apache-2.0. Privileged install only.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "tracee"
  },
  {
    binaryName: "tetragon",
    category: "DetectionRule",
    defaultVersion: "1.2.0",
    displayName: "Tetragon",
    dockerImage: "quay.io/cilium/tetragon",
    docsUrl: "https://tetragon.io/",
    gitRepo: "https://github.com/cilium/tetragon.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Cilium eBPF security observability. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "tetragon"
  },
  {
    binaryName: "inspec",
    category: "ControlValidation",
    defaultVersion: "6.8.0",
    displayName: "InSpec",
    dockerImage: "chef/inspec",
    docsUrl: "https://docs.chef.io/inspec/",
    gitRepo: "https://github.com/inspec/inspec.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Compliance-as-code. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "inspec"
  },
  {
    binaryName: "ghidra",
    category: "DetectionRule",
    defaultVersion: "11.2",
    displayName: "Ghidra",
    dockerImage: null,
    docsUrl: "https://ghidra-sre.org/",
    gitRepo: "https://github.com/NationalSecurityAgency/ghidra.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "NSA SRE reverse-engineering. Apache-2.0. Headless install.",
    policyStatus: "Enabled",
    runtimePreference: ["git", "binary"],
    toolId: "ghidra"
  },
  {
    binaryName: "binwalk",
    category: "DetectionRule",
    defaultVersion: "2.4.2",
    displayName: "Binwalk",
    dockerImage: null,
    docsUrl: "https://github.com/ReFirmLabs/binwalk",
    gitRepo: "https://github.com/ReFirmLabs/binwalk.git",
    license: "MIT",
    moduleIds: [],
    notes: "Firmware analysis. MIT.",
    pipPackage: "binwalk",
    policyStatus: "Enabled",
    runtimePreference: ["pip", "binary"],
    toolId: "binwalk"
  },
  {
    binaryName: "mitmproxy",
    category: "WebAppScan",
    defaultVersion: "11.0.0",
    displayName: "mitmproxy",
    dockerImage: "mitmproxy/mitmproxy",
    docsUrl: "https://mitmproxy.org/",
    gitRepo: "https://github.com/mitmproxy/mitmproxy.git",
    license: "MIT",
    moduleIds: [],
    notes: "Intercepting proxy. MIT. Operator-installed; not a default Community engine.",
    pipPackage: "mitmproxy",
    policyStatus: "Enabled",
    runtimePreference: ["pip", "docker"],
    toolId: "mitmproxy"
  },
  {
    binaryName: "zmap",
    category: "NetworkRecon",
    defaultVersion: "4.3.0",
    displayName: "ZMap",
    dockerImage: null,
    docsUrl: "https://zmap.io/",
    gitRepo: "https://github.com/zmap/zmap.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Internet-wide scanner. Apache-2.0. Catalog only — too aggressive for Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "zmap"
  },
  {
    binaryName: "zgrab2",
    category: "NetworkRecon",
    defaultVersion: "0.1.8",
    displayName: "ZGrab2",
    dockerImage: null,
    docsUrl: "https://github.com/zmap/zgrab2",
    gitRepo: "https://github.com/zmap/zgrab2.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Application-layer banner grab. Apache-2.0. Catalog; not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "zgrab"
  },
  {
    binaryName: "ssllabs-scan",
    category: "WebAppScan",
    defaultVersion: "1.5.0",
    displayName: "SSL Labs Scan",
    dockerImage: null,
    docsUrl: "https://github.com/ssllabs/ssllabs-scan",
    gitRepo: "https://github.com/ssllabs/ssllabs-scan.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Qualys SSL Labs client. Apache-2.0. Uses their API.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "ssllabs-scan"
  },
  {
    binaryName: "tcpdump",
    category: "DetectionRule",
    defaultVersion: "4.99.5",
    displayName: "tcpdump",
    dockerImage: "corfr/tcpdump",
    docsUrl: "https://www.tcpdump.org/",
    gitRepo: "https://github.com/the-tcpdump-group/tcpdump.git",
    license: "BSD-3-Clause",
    moduleIds: [],
    notes: "Packet capture. BSD-3-Clause.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "tcpdump"
  },
  {
    binaryName: "capa",
    category: "DetectionRule",
    defaultVersion: "7.1.0",
    displayName: "capa",
    dockerImage: null,
    docsUrl: "https://github.com/mandiant/capa",
    gitRepo: "https://github.com/mandiant/capa.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Mandiant capability detection on binaries. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "capa"
  },
  {
    binaryName: "cartography",
    category: "CloudSecurity",
    defaultVersion: "0.98.0",
    displayName: "Cartography",
    dockerImage: "ghcr.io/cartography-cncf/cartography",
    docsUrl: "https://cartography-cncf.github.io/cartography/",
    gitRepo: "https://github.com/cartography-cncf/cartography.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Asset graph. Apache-2.0. Service-style install.",
    pipPackage: "cartography",
    policyStatus: "Enabled",
    runtimePreference: ["pip", "docker"],
    toolId: "cartography"
  },
  {
    binaryName: "helm",
    category: "SupplyChain",
    defaultVersion: "3.16.0",
    displayName: "Helm",
    dockerImage: "alpine/helm",
    docsUrl: "https://helm.sh/",
    gitRepo: "https://github.com/helm/helm.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Helm CLI for chart inspection. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "helm"
  },
  {
    binaryName: "kustomize",
    category: "SupplyChain",
    defaultVersion: "5.5.0",
    displayName: "Kustomize",
    dockerImage: "registry.k8s.io/kustomize/kustomize",
    docsUrl: "https://kustomize.io/",
    gitRepo: "https://github.com/kubernetes-sigs/kustomize.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Kustomize CLI. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "kustomize"
  },
  {
    binaryName: "scalibr",
    category: "Dependency",
    defaultVersion: "0.1.5",
    displayName: "OSV-Scalibr",
    dockerImage: null,
    docsUrl: "https://github.com/google/osv-scalibr",
    gitRepo: "https://github.com/google/osv-scalibr.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Google OSV extraction library/CLI. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "osv-scalibr"
  },
  {
    binaryName: "whispers",
    category: "Secrets",
    defaultVersion: "2.3.0",
    displayName: "Whispers",
    dockerImage: null,
    docsUrl: "https://github.com/Skyscanner/whispers",
    gitRepo: "https://github.com/Skyscanner/whispers.git",
    license: "Apache-2.0",
    moduleIds: ["whispers.repo_secrets"],
    notes: "Skyscanner structured-secret scanner. Apache-2.0.",
    pipPackage: "whispers",
    policyStatus: "Enabled",
    runtimePreference: ["pip", "binary"],
    toolId: "whispers"
  },
  {
    binaryName: "security-scan",
    category: "ExposureValidation",
    defaultVersion: "5.6.7",
    displayName: "Security Code Scan",
    dockerImage: null,
    docsUrl: "https://security-code-scan.github.io/",
    gitRepo: "https://github.com/security-code-scan/security-code-scan.git",
    license: "LGPL-3.0",
    licenseUrl:
      "https://github.com/security-code-scan/security-code-scan/blob/master/LICENSE",
    moduleIds: [],
    notes: ".NET SAST. LGPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["binary", "git"],
    toolId: "security-code-scan"
  },
  {
    binaryName: "insider",
    category: "ExposureValidation",
    defaultVersion: "3.0.0",
    displayName: "Insider",
    dockerImage: "insidersec/insider",
    docsUrl: "https://github.com/insidersec/insider",
    gitRepo: "https://github.com/insidersec/insider.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Insider SAST. Apache-2.0.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "insider"
  },
  {
    binaryName: "uncover",
    category: "ASV_EASM",
    defaultVersion: "1.0.9",
    displayName: "uncover",
    dockerImage: "projectdiscovery/uncover",
    docsUrl: "https://github.com/projectdiscovery/uncover",
    gitRepo: "https://github.com/projectdiscovery/uncover.git",
    license: "MIT",
    moduleIds: [],
    notes: "Passive search-engine asset uncover. MIT.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "uncover"
  },
  {
    binaryName: "jaeles",
    category: "WebAppScan",
    defaultVersion: "0.17.1",
    displayName: "Jaeles",
    dockerImage: "jaeles/jaeles",
    docsUrl: "https://github.com/jaeles-project/jaeles",
    gitRepo: "https://github.com/jaeles-project/jaeles.git",
    license: "MIT",
    moduleIds: [],
    notes: "Signature-based web scanner. MIT. Catalog; not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "jaeles"
  },
  {
    binaryName: "arjun",
    category: "WebAppScan",
    defaultVersion: "2.2.6",
    displayName: "Arjun",
    dockerImage: null,
    docsUrl: "https://github.com/s0md3v/Arjun",
    gitRepo: "https://github.com/s0md3v/Arjun.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/s0md3v/Arjun/blob/master/LICENSE",
    moduleIds: [],
    notes: "HTTP parameter discovery. GPL-3.0 — license accept. Not Community.",
    pipPackage: "arjun",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["pip", "git"],
    toolId: "arjun"
  },
  {
    binaryName: "gobuster",
    category: "WebAppScan",
    defaultVersion: "3.6.0",
    displayName: "Gobuster",
    dockerImage: "ghcr.io/oj/gobuster",
    docsUrl: "https://github.com/OJ/gobuster",
    gitRepo: "https://github.com/OJ/gobuster.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "Dir/DNS brute. Apache-2.0. Catalog only — not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "gobuster"
  },
  {
    binaryName: "feroxbuster",
    category: "WebAppScan",
    defaultVersion: "2.11.0",
    displayName: "feroxbuster",
    dockerImage: "epi052/feroxbuster",
    docsUrl: "https://github.com/epi052/feroxbuster",
    gitRepo: "https://github.com/epi052/feroxbuster.git",
    license: "MIT",
    moduleIds: [],
    notes: "Content discovery. MIT. Catalog only — not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "docker"],
    toolId: "feroxbuster"
  },
  {
    binaryName: "cloudfox",
    category: "CloudSecurity",
    defaultVersion: "1.15.0",
    displayName: "CloudFox",
    dockerImage: null,
    docsUrl: "https://github.com/BishopFox/cloudfox",
    gitRepo: "https://github.com/BishopFox/cloudfox.git",
    license: "MIT",
    moduleIds: [],
    notes: "Cloud situational awareness. MIT. Catalog; not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["binary", "git"],
    toolId: "cloudfox"
  },
  {
    binaryName: "kube-hunter",
    category: "CloudSecurity",
    defaultVersion: "0.6.8",
    displayName: "kube-hunter",
    dockerImage: "aquasec/kube-hunter",
    docsUrl: "https://github.com/aquasecurity/kube-hunter",
    gitRepo: "https://github.com/aquasecurity/kube-hunter.git",
    license: "Apache-2.0",
    moduleIds: [],
    notes: "K8s attack-surface hunter. Apache-2.0. Catalog; not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "binary"],
    toolId: "kube-hunter"
  },
  {
    binaryName: "trufflehog",
    category: "Secrets",
    defaultVersion: "3.88.0",
    displayName: "TruffleHog",
    dockerImage: "trufflesecurity/trufflehog",
    docsUrl: "https://github.com/trufflesecurity/trufflehog",
    gitRepo: "https://github.com/trufflesecurity/trufflehog.git",
    license: "AGPL-3.0",
    licenseUrl: "https://github.com/trufflesecurity/trufflehog/blob/main/LICENSE",
    moduleIds: ["trufflehog.repo_secrets"],
    notes: "AGPL secrets scanner. Tenant accepts SPDX then we pull official pin.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "trufflehog"
  },
  {
    binaryName: "hadolint",
    category: "SupplyChain",
    defaultVersion: "2.12.0",
    displayName: "Hadolint",
    dockerImage: "hadolint/hadolint",
    docsUrl: "https://github.com/hadolint/hadolint",
    gitRepo: "https://github.com/hadolint/hadolint.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/hadolint/hadolint/blob/master/LICENSE",
    moduleIds: ["hadolint.dockerfile"],
    notes: "Dockerfile linter. GPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "hadolint"
  },
  {
    binaryName: "osqueryi",
    category: "DetectionRule",
    defaultVersion: "5.13.1",
    displayName: "osquery",
    dockerImage: null,
    docsUrl: "https://www.osquery.io/",
    gitRepo: "https://github.com/osquery/osquery.git",
    license: "GPL-2.0-only WITH Linux-syscall-note OR Apache-2.0",
    licenseUrl: "https://github.com/osquery/osquery/blob/master/LICENSE",
    moduleIds: [],
    notes: "Host SQL. Dual GPL/Apache — license accept before install.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["binary", "git"],
    toolId: "osquery"
  },
  {
    binaryName: "suricata",
    category: "DetectionRule",
    defaultVersion: "7.0.7",
    displayName: "Suricata",
    dockerImage: "jasonish/suricata",
    docsUrl: "https://suricata.io/",
    gitRepo: "https://github.com/OISF/suricata.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/OISF/suricata/blob/master/COPYING",
    moduleIds: [],
    notes: "IDS/IPS engine. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "suricata"
  },
  {
    binaryName: "wazuh-agent",
    category: "DetectionRule",
    defaultVersion: "4.9.2",
    displayName: "Wazuh",
    dockerImage: "wazuh/wazuh-manager",
    docsUrl: "https://wazuh.com/",
    gitRepo: "https://github.com/wazuh/wazuh.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/wazuh/wazuh/blob/master/LICENSE",
    moduleIds: [],
    notes: "XDR/SIEM. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "wazuh"
  },
  {
    binaryName: "rustscan",
    category: "NetworkRecon",
    defaultVersion: "2.3.0",
    displayName: "RustScan",
    dockerImage: "rustscan/rustscan",
    docsUrl: "https://github.com/RustScan/RustScan",
    gitRepo: "https://github.com/RustScan/RustScan.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/RustScan/RustScan/blob/master/LICENSE",
    moduleIds: ["rustscan.port_inventory"],
    notes: "Fast port inventory. GPL-3.0 — license accept. Not Community default.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "rustscan"
  },
  {
    binaryName: "wapiti",
    category: "WebAppScan",
    defaultVersion: "3.2.2",
    displayName: "Wapiti",
    dockerImage: null,
    docsUrl: "https://wapiti-scanner.github.io/",
    gitRepo: "https://github.com/wapiti-scanner/wapiti.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/wapiti-scanner/wapiti/blob/master/LICENSE",
    moduleIds: [],
    notes: "Web vuln scanner. GPL-2.0. License accept; not Community start.",
    pipPackage: "wapiti3",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["pip", "git"],
    toolId: "wapiti"
  },
  {
    binaryName: "sslscan",
    category: "WebAppScan",
    defaultVersion: "2.1.5",
    displayName: "sslscan",
    dockerImage: "dweomer/sslscan",
    docsUrl: "https://github.com/rbsec/sslscan",
    gitRepo: "https://github.com/rbsec/sslscan.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/rbsec/sslscan/blob/master/Licence",
    moduleIds: ["sslscan.tls_probe"],
    notes: "TLS cipher inventory. GPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "sslscan"
  },
  {
    binaryName: "lynis",
    category: "ControlValidation",
    defaultVersion: "3.1.2",
    displayName: "Lynis",
    dockerImage: "cisofy/lynis",
    docsUrl: "https://cisofy.com/lynis/",
    gitRepo: "https://github.com/CISOfy/lynis.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/CISOfy/lynis/blob/master/LICENSE",
    moduleIds: ["lynis.host_audit"],
    notes: "Host audit. GPL-3.0 — license accept. Runner-local.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "lynis"
  },
  {
    binaryName: "gvm-cli",
    category: "ExternalExposure",
    defaultVersion: "23.0.0",
    displayName: "OpenVAS / GVM",
    dockerImage: "greenbone/openvas-scanner",
    docsUrl: "https://www.openvas.org/",
    gitRepo: "https://github.com/greenbone/openvas-scanner.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/greenbone/openvas-scanner/blob/main/LICENSE",
    moduleIds: [],
    notes: "Vulnerability scanner. GPL-2.0 — license accept. Not Community start.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "openvas"
  },
  {
    binaryName: "tshark",
    category: "DetectionRule",
    defaultVersion: "4.4.0",
    displayName: "tshark",
    dockerImage: "ghcr.io/wireshark/wireshark",
    docsUrl: "https://www.wireshark.org/",
    gitRepo: "https://github.com/wireshark/wireshark.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/wireshark/wireshark/blob/master/COPYING",
    moduleIds: [],
    notes: "Wireshark CLI. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "tshark"
  },
  {
    binaryName: "fail2ban-client",
    category: "DetectionRule",
    defaultVersion: "1.1.0",
    displayName: "Fail2ban",
    dockerImage: "crazymax/fail2ban",
    docsUrl: "https://www.fail2ban.org/",
    gitRepo: "https://github.com/fail2ban/fail2ban.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/fail2ban/fail2ban/blob/master/COPYING",
    moduleIds: [],
    notes: "Log ban agent. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "fail2ban"
  },
  {
    binaryName: "clamscan",
    category: "DetectionRule",
    defaultVersion: "1.4.1",
    displayName: "ClamAV",
    dockerImage: "clamav/clamav",
    docsUrl: "https://www.clamav.net/",
    gitRepo: "https://github.com/Cisco-Talos/clamav.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/Cisco-Talos/clamav/blob/main/COPYING.txt",
    moduleIds: [],
    notes: "Antivirus engine. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "clamav"
  },
  {
    binaryName: "vuls",
    category: "Dependency",
    defaultVersion: "0.26.0",
    displayName: "Vuls",
    dockerImage: "vuls/vuls",
    docsUrl: "https://vuls.io/",
    gitRepo: "https://github.com/future-architect/vuls.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/future-architect/vuls/blob/master/LICENSE",
    moduleIds: [],
    notes: "Agentless Linux vuln scanner. GPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "vuls"
  },
  {
    binaryName: "sf.py",
    category: "ASV_EASM",
    defaultVersion: "4.0.0",
    displayName: "SpiderFoot",
    dockerImage: "spiderfoot/spiderfoot",
    docsUrl: "https://www.spiderfoot.net/",
    gitRepo: "https://github.com/smicallef/spiderfoot.git",
    license: "MIT",
    moduleIds: [],
    notes: "OSINT recon. MIT. Catalog; not Community start.",
    policyStatus: "Enabled",
    runtimePreference: ["docker", "git"],
    toolId: "spiderfoot"
  },
  {
    binaryName: "findomain",
    category: "ASV_EASM",
    defaultVersion: "9.0.4",
    displayName: "Findomain",
    dockerImage: "edu4rdshl/findomain",
    docsUrl: "https://github.com/Findomain/Findomain",
    gitRepo: "https://github.com/Findomain/Findomain.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/Findomain/Findomain/blob/master/LICENSE",
    moduleIds: [],
    notes: "Subdomain enum. GPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "findomain"
  },
  {
    binaryName: "cve-bin-tool",
    category: "Dependency",
    defaultVersion: "3.4",
    displayName: "CVE Binary Tool",
    dockerImage: "intel/cve-bin-tool",
    docsUrl: "https://cve-bin-tool.readthedocs.io/",
    gitRepo: "https://github.com/intel/cve-bin-tool.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/intel/cve-bin-tool/blob/main/LICENSE",
    moduleIds: ["cve_bin_tool.binary_cves"],
    notes: "Intel binary CVE scanner. GPL-3.0 — license accept.",
    pipPackage: "cve-bin-tool",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["pip", "docker"],
    toolId: "cve-bin-tool"
  },
  {
    binaryName: "nodejsscan",
    category: "ExposureValidation",
    defaultVersion: "4.8",
    displayName: "nodejsscan",
    dockerImage: "opensecurity/nodejsscan",
    docsUrl: "https://github.com/ajinabraham/nodejsscan",
    gitRepo: "https://github.com/ajinabraham/nodejsscan.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/ajinabraham/nodejsscan/blob/master/LICENSE",
    moduleIds: [],
    notes: "Node.js SAST. GPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "nodejsscan"
  },
  {
    binaryName: "radare2",
    category: "DetectionRule",
    defaultVersion: "5.9.6",
    displayName: "radare2",
    dockerImage: "radare/radare2",
    docsUrl: "https://www.radare.org/",
    gitRepo: "https://github.com/radareorg/radare2.git",
    license: "LGPL-3.0",
    licenseUrl: "https://github.com/radareorg/radare2/blob/master/COPYING",
    moduleIds: [],
    notes: "Reverse-engineering framework. LGPL-3.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "binary"],
    toolId: "radare2"
  },
  {
    binaryName: "ossec-control",
    category: "DetectionRule",
    defaultVersion: "3.7.0",
    displayName: "OSSEC",
    dockerImage: "atomicorp/ossec-docker",
    docsUrl: "https://www.ossec.net/",
    gitRepo: "https://github.com/ossec/ossec-hids.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/ossec/ossec-hids/blob/master/LICENSE",
    moduleIds: [],
    notes: "HIDS. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "ossec"
  },
  {
    binaryName: "vol",
    category: "DetectionRule",
    defaultVersion: "2.8.0",
    displayName: "Volatility 3",
    dockerImage: null,
    docsUrl: "https://volatility3.readthedocs.io/",
    gitRepo: "https://github.com/volatilityfoundation/volatility3.git",
    license: "custom-volatility / GPL-compatible",
    licenseUrl: "https://github.com/volatilityfoundation/volatility3/blob/develop/LICENSE.txt",
    moduleIds: [],
    notes: "Memory forensics. License accept before install.",
    pipPackage: "volatility3",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["pip", "git"],
    toolId: "volatility3"
  },
  {
    binaryName: "recon-ng",
    category: "ASV_EASM",
    defaultVersion: "5.1.2",
    displayName: "Recon-ng",
    dockerImage: null,
    docsUrl: "https://github.com/lanmaster53/recon-ng",
    gitRepo: "https://github.com/lanmaster53/recon-ng.git",
    license: "GPL-3.0",
    licenseUrl: "https://github.com/lanmaster53/recon-ng/blob/master/LICENSE",
    moduleIds: [],
    notes: "Recon framework. GPL-3.0 — license accept. Not Community start.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["git", "binary"],
    toolId: "recon-ng"
  },
  {
    binaryName: "theHarvester",
    category: "ASV_EASM",
    defaultVersion: "4.6.0",
    displayName: "theHarvester",
    dockerImage: "laramies/theharvester",
    docsUrl: "https://github.com/laramies/theHarvester",
    gitRepo: "https://github.com/laramies/theHarvester.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/laramies/theHarvester/blob/master/README.md",
    moduleIds: [],
    notes: "OSINT harvester. GPL-2.0 — license accept.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["docker", "git"],
    toolId: "theharvester"
  },
  {
    binaryName: "dirsearch",
    category: "WebAppScan",
    defaultVersion: "0.4.3",
    displayName: "dirsearch",
    dockerImage: null,
    docsUrl: "https://github.com/maurosoria/dirsearch",
    gitRepo: "https://github.com/maurosoria/dirsearch.git",
    license: "GPL-2.0",
    licenseUrl: "https://github.com/maurosoria/dirsearch/blob/master/LICENSE",
    moduleIds: [],
    notes: "Web path discovery. GPL-2.0. License accept; not Community start.",
    policyStatus: "RequiresLegalReview",
    runtimePreference: ["git", "pip"],
    pipPackage: "dirsearch",
    toolId: "dirsearch"
  }
];

export const SECURITY_CATALOG_EXPANSION_TOOL_DEFINITIONS =
  EXPANSION_TOOLS.map((tool) => ({
    binaryName: tool.binaryName,
    category: tool.category,
    defaultVersion: tool.defaultVersion,
    displayName: tool.displayName,
    dockerImage: tool.dockerImage,
    docsUrl: tool.docsUrl,
    gitRepo: tool.gitRepo,
    license: tool.license,
    licenseUrl: tool.licenseUrl,
    moduleIds: tool.moduleIds,
    notes: tool.notes,
    npmPackage: tool.npmPackage ?? null,
    phase: "Current" as const,
    pipPackage: tool.pipPackage ?? null,
    policyStatus: tool.policyStatus,
    runtimePreference: tool.runtimePreference,
    toolId: tool.toolId,
    upstreamLicenseUrl: tool.licenseUrl,
    userLicenseAcceptanceRequired: tool.policyStatus === "RequiresLegalReview"
  })) satisfies OpenSourceToolDefinition[];

export const SECURITY_CATALOG_EXPANSION_CAPABILITIES: OpenSourceCapability[] =
  EXPANSION_TOOLS.map((tool) => ({
    apiRoutes: [
      "/api/v1/third-party-tools",
      "/api/v1/modules",
      "/api/v1/community/validation-suite"
    ],
    capabilityId: `${tool.toolId}.catalog`,
    description: tool.notes,
    evidenceTypes: ["NormalizedEvidence"],
    executionMode: "ControlPlane",
    featureTags: ["catalog", tool.category.toLowerCase()],
    inputSchemaRef: "CatalogTargetSchema",
    interfaceKind:
      tool.moduleIds.length > 0 ? "ValidationModule" : "Collector",
    missionTypes: ["ValidationSnapshot", "ExposureValidation"],
    moduleId: tool.moduleIds[0] ?? null,
    name: tool.displayName,
    outputSchemaRef: "ModuleOutputSchema",
    phase: "Current",
    requiredIntegrations: [],
    requiredScopes: ["Repository"],
    safetyLevels: ["PassiveReadOnly"],
    status: tool.moduleIds.length > 0 ? "Implemented" : "Planned",
    toolId: tool.toolId
  }));
