export {
  DETECTION_CORRELATION_LAW,
  DETECTION_CORRELATION_MARKER_PATTERN,
  DetectionCorrelationEventOutcomeSchema,
  DetectionCorrelationStageSchema,
  DetectionCorrelationVerdictSchema,
  OBSERVER_HEALTH_LAST_VALIDATED_FALLBACK,
  ObserverHealthStatusSchema,
  buildDetectionRunStepMarker,
  correlateDetectionObservation,
  correlateStimulusObservation,
  evaluateObserverHealthWindow,
  eventMatchesCorrelationKeys,
  gateMissedByObserverHealth,
  isObserverOutage,
  mapDetectionCorrelationToEffectiveness,
  observerHealthAllowsMissed,
  parseDetectionRunStepMarker,
  type DetectionCorrelationEvent,
  type DetectionCorrelationEventOutcome,
  type DetectionCorrelationInject,
  type DetectionCorrelationInput,
  type DetectionCorrelationObservation,
  type DetectionCorrelationObserver,
  type DetectionCorrelationResult,
  type DetectionCorrelationStage,
  type DetectionCorrelationVerdict,
  type ObserverHealthCoverage,
  type ObserverHealthSample,
  type ObserverHealthStatus,
  type ObserverHealthWindowAssessment
} from "@periscan/shared";
